### ISSUE TITLE
Can not add md-sets via the category context menu

### ISSUE THREAD

**Issue by GIT-STATA** [holgerbrandl/opencards#20]
## OpenCards Version 2.4

*I can't add a Markdown card set.* Nothing happens and no errors 'pop up'.
I can add card sets as *.ppt. Everything works perfectly with those type of files.... 

I have a Example.md file ([url] http://opencards.info), which looks like this: 

```

## What is a blocking factor?

A blocking factor is a source of variability that is not of primary interest to the experimenter 

```

*So, I wondering what exactly the problem is?*
**Thanks to everyone!!!**

**Comment by holgerbrandl** [comment]
Great that a first user has discovered the recently added markdown functionality in OpenCards. :-)

The problem seems that adding md-sets via the context menu of the category tree is not working correctly yet.  I'll fix this asap. 

In the meantime you can simply drag and drop the your md-file into OpenCards. This works for me:
![image](https://cloud.githubusercontent.com/assets/200952/14881471/6d398ed8-0d34-11e6-93a9-cfee852f6c17.png)

**Comment by GIT-STATA** [comment]
I do not know why... **but this does not function on my system...**

> 'contain invalid  flashcards' 

**Thanks for you great work!!!**

**Comment by holgerbrandl** [comment]
Could you attach your example md file to the Ticket?

GIT-STATA <notifications@github.com> schrieb am Do., 28. Apr. 2016, 2:37
nachm.:

**Comment by GIT-STATA** [comment]
[OpenCards.md.txt](https://github.com/holgerbrandl/opencards/files/242748/OpenCards.md.txt)

**SURE...** But it is really as simple as I told... 

**THANKS**

**Comment by holgerbrandl** [comment]
Indeed it is simple, however, I wanted to make sure that OpenCards does not stumble over file-encodings etc. And the good/interesting news is, that your file works for me without any changes:
![image](https://cloud.githubusercontent.com/assets/200952/14921659/8dabb3b2-0e33-11e6-80df-db4cc4ddd722.png)

What are your markdown settings in OpenCards? See Preferences --> Advanced --> Markdown:
![image](https://cloud.githubusercontent.com/assets/200952/14921734/ef80fe80-0e33-11e6-9264-c9b1c20cf79f.png)

Unrelated to your problem, but worth mentioning: It's not intended that users/you can add files with the suffix .md.txt. I'll make it more stringent for the next release to just support *.md and *.ppt. see ticket #21

**Comment by GIT-STATA** [comment]
When ever I try to change it, it falls back to the value **false**???

![auswahl_076](https://cloud.githubusercontent.com/assets/17551564/14922914/823bb8e0-0e3a-11e6-822b-8f477504ba70.jpg)

**Comment by holgerbrandl** [comment]
Thank you for you feedback. I've traced down the problem and will prepare a new release over the weekend. I'll let you know once it's ready.

**Comment by holgerbrandl** [comment]
I've released an improved version which addresses all your reported problems:
* adding sets via context menu
* preferences are not stored
* markdown sets are not processed correctly

Please download a new version from https://github.com/holgerbrandl/opencards/releases/tag/v2.5 and feel welcome to reopen this ticket if you still struggle to use opencards. Thank you for your patience!

**Comment by GIT-STATA** [comment]
**the following problem occurred while I was using OpenCards:**

OpenCards version: 2.5
Platform: Linux 3.10.0-327.13.1.el7.x86_64Java Version: 1.8.0_91 - Oracle Corporation

Thread[AWT-EventQueue-0,6,main]

java.lang.NoClassDefFoundError: javafx/scene/Parent

info.opencards.CardFileBackend.getSlideManager(CardFileBackend.java:52)
info.opencards.ui.AbstractLearnDialog.prepareFileSession(AbstractLearnDialog.java:159)
info.opencards.core.LearnProcessManager.startProcessing(LearnProcessManager.java:93)
info.opencards.core.LearnProcessManager.startProcessing(LearnProcessManager.java:63)
info.opencards.ui.actions.StartLearningAction.learnCardFiles(StartLearningAction.java:166)
info.opencards.ui.actions.StartLearningAction.actionPerformed(StartLearningAction.java:64)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) 


**I do not know what to do?**
**Thanks!**
