### ISSUE TITLE
 Can not add md-sets via the category context menu #20 

### ISSUE THREAD

**Issue by GIT-STATA** [holgerbrandl/opencards#23]
## I am referring to the closed issue "Can not add md-sets via the category context menu #20"

The following problem occurred while I was using OpenCards:

OpenCards version: 2.5
Platform: Linux 3.10.0-327.13.1.el7.x86_64Java Version: 1.8.0_91 - Oracle Corporation

Thread[AWT-EventQueue-0,6,main]

java.lang.NoClassDefFoundError: javafx/scene/Parent

info.opencards.CardFileBackend.getSlideManager(CardFileBackend.java:52)
info.opencards.ui.AbstractLearnDialog.prepareFileSession(AbstractLearnDialog.java:159)
info.opencards.core.LearnProcessManager.startProcessing(LearnProcessManager.java:93)
info.opencards.core.LearnProcessManager.startProcessing(LearnProcessManager.java:63)
info.opencards.ui.actions.StartLearningAction.learnCardFiles(StartLearningAction.java:166)
info.opencards.ui.actions.StartLearningAction.actionPerformed(StartLearningAction.java:64)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)

I do not know what to do?
**Thanks!**

**Comment by holgerbrandl** [comment]
I've seen your comment in #20 but having a separate ticket is also fine. I've already started looking into it. It works for me on Ubuntu, and I think it's linux distribution specific. 

Did you install java as indicated on
http://askubuntu.com/questions/521145/how-to-install-oracle-java-on-ubuntu-14-04
?

Could you open a terminal and run 
```
find $JAVA_HOME | grep fx   
```
and attach the result to this ticket?

**Comment by GIT-STATA** [comment]
When I run

> find $JAVA_HOME | grep fx 

there is nothing!


> whereis java

java: /usr/bin/java /usr/lib/java /etc/java /usr/share/java 
/usr/share/man/man1/java.1.gz


I will install Java (Oracle) on monday when I will be back... I will see...


Thanks!

Best!




Am 04.05.2016 um 15:54 schrieb Holger Brandl:

**Comment by GIT-STATA** [comment]
**Hi,** 

**after I have installed (Oracle) Java everything works fine! I do not have any issues...** 
*Thank you very much!!!*

**Comment by holgerbrandl** [comment]
That's great news. Feel welcome if you've questions or suggestions to make OpenCards even better.
