### ISSUE TITLE
Ubuntu dependencies

### ISSUE THREAD

**Issue by claell** [holgerbrandl/opencards#25]
Currently I cannot install opencards deb file on Ubuntu 16.04 since there does not seem candidates for the openjdk dependencies.

**Comment by holgerbrandl** [comment]
good point. I'll have a look asap

**Comment by claell** [comment]
Thanks

**Comment by holgerbrandl** [comment]
Fixed in v2.5.1. Also see https://github.com/holgerbrandl/opencards#linux
