### ISSUE TITLE
Windows build FAILS

### ISSUE THREAD

**Issue by tomanizer** [holgerbrandl/opencards#31]
The windows build opencards-2.5.1-windows.zip:

After extraction
OpenCards.exe fails with 
"Could not find main class: info.opencardsOpenCards. Program will exit" on Windows 7.

**Comment by tomanizer** [comment]
when starting it from the command line it fails with UnsupportedClassVersionError: info/opencards?OpenCards : Unsupported major.minar version 52.0

**Comment by tomanizer** [comment]
java version "1.6.0_121"
Java(TM) SE Runtime Environment (build 1.6.0_121-b09)

**Comment by holgerbrandl** [comment]
Are you using java8?

**Comment by tomanizer** [comment]
No. Our production version is Java 6. So is this just a version issue? Java8 is required to run it?
thanks a lot for this program by the way. great effort!

**Comment by holgerbrandl** [comment]
yes java 8 is required. I think java6 had it's time, but it's dated now.

**Comment by vavd** [comment]
OpenCards.exe doesn't start on win 7. No messages at all.
How to figure out where is the issue?

**Comment by holgerbrandl** [comment]
@vavd Do you have Java installed

**Comment by vavd** [comment]
@holgerbrandl Yes, I do:
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Before I installed Java it'd showed me the message that Java is not available

**Comment by holgerbrandl** [comment]
Not sure,  does it directly from the jar when being built from the sources?

**Comment by vavd** [comment]
Sorry, I didn't try to build it. Just use binary.

**Comment by holgerbrandl** [comment]
Java 9/10 is now required to build OC
