### ISSUE TITLE
HTML Render Frame

### ISSUE THREAD

**Issue by p1tt1** [holgerbrandl/opencards#33]
Why use the HTML Renderer not the full width/height within the window?

**Comment by holgerbrandl** [comment]
I does for me. Could send a screenshot?

p1tt1 <notifications@github.com> schrieb am Do., 23. März 2017, 19:32:

**Comment by p1tt1** [comment]
![screenshoot](https://cloud.githubusercontent.com/assets/1847816/24286281/cfefdc5a-1074-11e7-8ef0-469d1898ef5a.png)

**Comment by holgerbrandl** [comment]
What happens if you resize the frame of opencards?

-Holger

p1tt1 <notifications@github.com> schrieb am Fr., 24. März 2017 um 09:32 Uhr:

**Comment by p1tt1** [comment]
the render frame within the opencards window is fix (irrespective of the windoe size)

![screenshoot_2](https://cloud.githubusercontent.com/assets/1847816/24300387/9bbb213c-10ac-11e7-9fa3-d857311ea0ad.png)

**Comment by holgerbrandl** [comment]
I've noticed a similar issue on macos occasionally, but resizing the window
usually caused a correct repainting of the content.

Would you mind sending me the markdown example file (or just an excerpt)?
What linux distro are you using?

-Holger

p1tt1 <notifications@github.com> schrieb am Fr., 24. März 2017 um 16:14 Uhr:

**Comment by p1tt1** [comment]
this is the file:
[test.txt](https://github.com/holgerbrandl/opencards/files/871802/test.txt)

I'm using arch linux with a tiling window manager behalf i3.

**Comment by holgerbrandl** [comment]
Confirmed, same for me. I'll have a look asap.
