### ISSUE TITLE
Spelling errors on the website

### ISSUE THREAD

**Issue by samWson** [holgerbrandl/opencards#35]
I've spotted a few spelling mistakes on the opencards.info website. I'd be happy to correct them for you, except I can't find the source code. Is the website source code in this repo or is it somewhere else?

**Comment by holgerbrandl** [comment]
Hi Sam, sorry for the typos. The website is sitting in the gh-pages branch. https://github.com/holgerbrandl/opencards/tree/gh-pages
I'd looking forward to your PR!

**Comment by samWson** [comment]
@holgerbrandl I'm currently working on the website right now. I'm going through the pages and making edits to make it read better as English. Small things like rouge white spaces, substituting more grammatically correct words, punctuation etc. I try to have a pull request ready by the end of the weekend.

**Comment by samWson** [comment]
@holgerbrandl I've made numerous edits that improve the readability of the website for the English speaking user. These are very small changes all over the files. Correcting spelling, punctuation, swapping words etc. 
The first pull request is ready #37. Have a look and let me know what you think. I have a few more HTML files to review before this issue can be closed. 
By the way, I found a open source spell checking and grammar checking tool online, [LanguageTool ](https://languagetool.org/). It's been very helpful for making these edits, even for a native English speaker.

**Comment by holgerbrandl** [comment]
Thanks a lot for your contribution.

**Comment by samWson** [comment]
@holgerbrandl I've finished going through the remaining HTML files for the website, and have made edits to the spelling and grammar. My pull request is ready for review #38.

**Comment by holgerbrandl** [comment]
Thanks @samWson for the PR!
