### ISSUE TITLE
Auto discover new cards in directory tree

### ISSUE THREAD

**Issue by borisrorsvort** [holgerbrandl/opencards#41]
Platform: osx 10.12.6

The setting to auto discover cards in directory tree is not being saved. It’s unticked rebooting the application.

**Comment by holgerbrandl** [comment]
I already on 10.13.4, and there the preferences are persisted correctly. Does it remeber other values in the preferences?

**Comment by borisrorsvort** [comment]
Nope, no other advanced settings gets saved

**Comment by holgerbrandl** [comment]
What is your version of Java?

**Comment by borisrorsvort** [comment]
![screen shot 2018-06-04 at 13 29 06](https://user-images.githubusercontent.com/39081/40915167-528d1a40-67fb-11e8-807d-71433d8b12b3.png)

**Comment by borisrorsvort** [comment]
Did you had a chance to look it up?

**Comment by holgerbrandl** [comment]
Sorry not yet. Without being able to reproduce the problem on my end, it's really hard to get started.
